# Generated by Django 5.1.3 on 2024-11-14 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AlterModelOptions(
            name='barcodescan',
            options={'ordering': ['time_taken'], 'verbose_name': 'Barcode Scan', 'verbose_name_plural': 'Barcode Scans'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterModelOptions(
            name='qrcodedata',
            options={'verbose_name': 'QR Code Data', 'verbose_name_plural': 'QR Code Data'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(help_text='Enter the main description (use paragraphs separated by \\n)', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(help_text='Upload an image for the about section', upload_to='about_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(help_text='Enter a subtitle for the about section', max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='barcodescan',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_scans', to='Events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='barcodescan',
            name='scan_time',
            field=models.DateTimeField(verbose_name='Scan Time'),
        ),
        migrations.AlterField(
            model_name='barcodescan',
            name='time_taken',
            field=models.CharField(blank=True, help_text='Time taken to complete the event', max_length=15, null=True, verbose_name='Time Taken'),
        ),
        migrations.AlterField(
            model_name='barcodescan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_scans', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Event Creator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Select the date of the event', verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, help_text='Upload an image for the event (optional)', null=True, upload_to='event_images/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Enter the location/venue of the event', max_length=255, verbose_name='Event Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Enter the name of the event', max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Enter the start time of the event', null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stop_time',
            field=models.DateTimeField(blank=True, help_text='Enter the end time of the event', null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR Code Data'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='about_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Events.aboutsection', verbose_name='About Section'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='number',
            field=models.CharField(help_text='Enter the statistic number (e.g., 300+)', max_length=50, verbose_name='Statistic Number'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='text',
            field=models.CharField(help_text='Enter the statistic description', max_length=100, verbose_name='Statistic Description'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('user', 'event')},
        ),
    ]
